import Mathlib
import Mathlib.CategoryTheory.Whiskering
import Mathlib.LinearAlgebra.Basis.Basic
import HomologyLean.SingularHomology.Representable
import Mathlib.Tactic.ErwQuestion
import Mathlib.Algebra.Homology.ShortComplex.FunctorEquivalence

/-!
# Two formulations of the acyclic models theorem

This file contains statements, rather than proofs, of:

1. the basis-and-models formulation used by the Lean 3 Brouwer fixed-point
   development;
2. a categorical comparison theorem relative to a class of model-projective
   objects.

The second statement uses augmented complexes.  When the augmentation object
is identified with zeroth homology, it says the same thing as lifting a map on
zeroth homology.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits Representable CategoryTheory.Functor

universe u w

namespace AcyclicModels

variable {C : Type u} [Category.{w} C]
variable {R : Type w} [CommRing R]


/--
The native representation of a naturally varying chain complex: a chain
complex in the functor category.  Its objectwise interpretation is
`K.asFunctor : C ⥤ ChainComplex (ModuleCat R) ℕ`.
-/

abbrev FunctorComplex :=
  ChainComplex (C ⥤ ModuleCat R) ℕ

-- /-- The natural isomorphism `K.homology j ≅ (K.sc' i j k).homology`
-- for all homological complexes `K` when `c.prev j = i` and `c.next j = k`. -/
-- noncomputable def homologyFunctorIso' [CategoryWithHomology C]
--     (hi : c.prev j = i) (hk : c.next j = k) :
--     homologyFunctor C c j ≅
--       shortComplexFunctor' C c i j k ⋙ ShortComplex.homologyFunctor C :=
--   homologyFunctorIso C c j ≪≫ Functor.isoWhiskerRight (natIsoSc' C c i j k hi hk) _

#check Functor.uncurry


noncomputable def functorEquivalence' (n : ℕ) :
  Functor.uncurry.obj (HomologicalComplex.complexOfFunctorsToFunctorToComplex (T := C) (V := ModuleCat.{w} R) (c := ComplexShape.down ℕ)) ⋙
    (HomologicalComplex.shortComplexFunctor (ModuleCat R) (ComplexShape.down ℕ) n) ≅
    Functor.uncurry.obj
      (HomologicalComplex.shortComplexFunctor
          (C ⥤ ModuleCat.{w} R) (ComplexShape.down ℕ) n ⋙
        (ShortComplex.functorEquivalence
          C (ModuleCat.{w} R)).functor)
     := by sorry

noncomputable def functorEquivalence (F : FunctorComplex (C := C) (R := R)) (n : ℕ) :
  (HomologicalComplex.complexOfFunctorsToFunctorToComplex.obj ) F ⋙
    (HomologicalComplex.shortComplexFunctor (_) (ComplexShape.down ℕ) n) ≅
    (((ShortComplex.functorEquivalence _ _).functor).obj ( (HomologicalComplex.shortComplexFunctor (_) (ComplexShape.down ℕ) n).obj F))

     := by
  exact ((Functor.curry).mapIso (functorEquivalence' n)).app F
/-! ## 1. The concrete basis-and-models formulation -/

section BasisVersion

variable {C : Type u} [Category.{w} C]
variable {R : Type w} [CommRing R]




abbrev FreeModule : Type w ⥤ ModuleCat R := (forget (ModuleCat R)).leftAdjoint



structure ModelObjects where
  Index : Type w
  model : Index → C


variable (P : ObjectProperty C) [HasCoproductsOfShape P.FullSubcategory (C ⥤ ModuleCat.{w} R)]



/--
`F` is freely generated by elements situated on chosen model objects.

For each `X`, the basis vectors of `F.obj X` are indexed by pairs consisting
of a model and a morphism from that model to `X`.
-/
-- structure ModelFree (M : ModelObjects) (F : C ⥤ ModuleCat R) where
--   basisElement : ∀ i, F.obj (M.model i)
--   basis : ∀ X, Module.Basis (Σ i, M.model i ⟶ X) R (F.obj X)
--   basis_apply : ∀ X i (f : M.model i ⟶ X),
--     basis X ⟨i, f⟩ = F.map f (basisElement i)


abbrev ModelFreeFunctor (M : ModelObjects (C := C)) : C ⥤ ModuleCat R :=
  ∐ fun i : M.Index => Hom[M.model i |-] ⋙ FreeModule



abbrev ModelFreeFunctor' : C ⥤ ModuleCat R :=
  ∐ fun i : P.FullSubcategory => Hom[ i.obj |-] ⋙ FreeModule

structure ModelFree (M : ModelObjects) (F : C ⥤ ModuleCat R) where
  iso : F ≅ ModelFreeFunctor M

structure ModelFree' (F : C ⥤ ModuleCat R) where
  iso : F ≅ ModelFreeFunctor' P

/-- A choice of a model basis in every chain degree. -/
abbrev ComplexModelFree (M : ModelObjects) (F : FunctorComplex (C := C) (R := R)) :=
  ∀ n, ModelFree M (F.X n)


structure ShortComplexModelFree  (F : ShortComplex (C ⥤ ModuleCat R)) where
  free₁ := ModelFree' P F.1
  free₂ := ModelFree' P F.2
  free₃ := ModelFree' P F.3



-- set_option trace.Meta.synthInstance true

/--
The target is acyclic on precisely the model objects needed by the two
inductive arguments.  This reproduces the hypotheses in the Lean 3 file.
-/
def AcyclicOnModels
    (M : ModelObjects (C := C))
    (G : FunctorComplex (C := C) (R := R)) : Prop :=
   ∀ i, ∀ n, 0 < n →
    ((G.asFunctor ⋙ (HomologicalComplex.shortComplexFunctor (_) (ComplexShape.down ℕ) n)).obj
      (M.model i)).Exact
    -- (G.asFunctor.obj (M.model i)).ExactAt n



-- variable (P) in
noncomputable def ShortComplexAcyclicOnModels (F : ShortComplex (C ⥤ ModuleCat R)) :=
  (F.map ((whiskeringLeft P.FullSubcategory C (ModuleCat.{w} R)).obj P.ι)).Exact




def EpiOnModels {F G : (C ⥤ ModuleCat R)}
  (α : F ⟶ G)
  (M : ModelObjects (C := C)) : Prop :=
  ∀ i, Epi (α.app (M.model i))


def EpiOnModels' {F G : (C ⥤ ModuleCat R)}
  (α : F ⟶ G) : Prop :=
  ∀ i, Epi (α.app (P.ι.obj i))


section Examples

def topologicalNSimplexModel : ModelObjects (C := TopCat.{w}) where
    Index := ULift.{w} ℕ
    model n :=
      SimplexCategory.toTop.obj (SimplexCategory.mk n.down)

-- def chainComplexModelFree : ModelFree topologicalNSimplexModel

end Examples

#check AlgebraicTopology.singularChainComplexFunctor
#check AlgebraicTopology.singularChainComplexFunctorAdjunction
-- set_option pp.all true


lemma ShortComplexProjectiveLift' {G G' : (C ⥤ ModuleCat R)}
  {M : P.FullSubcategory}
   (g : G ⟶ G') (hG : EpiOnModels' P g) (f : Hom[ M.obj |-] ⋙ FreeModule ⟶ G') :
    ∃ f' : Hom[ M.obj |-] ⋙ FreeModule ⟶ G, f' ≫ g = f := by
  let m := M.obj
  let idM : FreeModule.obj (m ⟶ m) :=
    (Adjunction.ofIsRightAdjoint (forget (ModuleCat R))).unit.app
      (m ⟶ m) (𝟙 m)
  let fm_idM := (f.app m) idM
  have hg : Function.Surjective (g.app m) :=
    (ModuleCat.epi_iff_surjective (g.app m)).mp (hG M)
  let adj := Adjunction.ofIsRightAdjoint (forget (ModuleCat R))
  choose f'_idM hf'_idM using (hg fm_idM)
  refine ⟨?_, ?_⟩
  · refine ⟨?_, ?_⟩
    · intro X
      exact (adj.homEquiv
        (m ⟶ X) (G.obj X)).symm
        (TypeCat.ofHom fun fm ↦ G.map fm f'_idM)
    · intro X Y h
      apply (Adjunction.ofIsRightAdjoint
        (forget (ModuleCat R))).homEquiv_naturality_right_square
      ext fm
      simp
  · apply NatTrans.ext
    funext X
    simp only [NatTrans.comp_app]
    apply (adj.homEquiv (m ⟶ X) (G'.obj X)).injective
    change (adj.homEquiv (m ⟶ X) (G'.obj X))
        ((adj.homEquiv (m ⟶ X) (G.obj X)).symm
          (TypeCat.ofHom fun fm ↦ G.map fm f'_idM) ≫ g.app X) = _
    rw [adj.homEquiv_naturality_right]
    simp only [Equiv.apply_symm_apply]
    ext fm
    change g.app X (G.map fm f'_idM) =
      f.app X (adj.unit.app (m ⟶ X) fm)
    simp only [Functor.id_obj]
    rw [NatTrans.naturality_apply, hf'_idM]
    let q : (m ⟶ m) ⟶ (m ⟶ X) := TypeCat.ofHom fun k ↦ k ≫ fm
    have hunit := ConcreteCategory.congr_hom (adj.unit.naturality q) (𝟙 m)
    change adj.unit.app (m ⟶ X) (q (𝟙 m)) =
      FreeModule.map q (adj.unit.app (m ⟶ m) (𝟙 m)) at hunit
    have hf := ConcreteCategory.congr_hom (f.naturality fm) idM
    change f.app X (FreeModule.map q idM) = G'.map fm fm_idM at hf
    rw [← hf, ← hunit]
    simp only [q, TypeCat.ofHom_apply, Category.id_comp]
    rfl

lemma ProjectiveLift' {G G' : (C ⥤ ModuleCat R)} {M : ModelObjects (C := C)}
  {i : M.Index}
   (g : G ⟶ G') (hG : EpiOnModels g M) (f : Hom[M.model i |-] ⋙ FreeModule ⟶ G') :
    ∃ f' : Hom[M.model i |-] ⋙ FreeModule ⟶ G, f' ≫ g = f := by
  let m := M.model i
  let idM : FreeModule.obj (m ⟶ m) :=
    (Adjunction.ofIsRightAdjoint (forget (ModuleCat R))).unit.app
      (m ⟶ m) (𝟙 m)
  let idM : FreeModule.obj (m ⟶ m) :=
    (Adjunction.ofIsRightAdjoint (forget (ModuleCat R))).unit.app
      (m ⟶ m) (𝟙 m)
  let fm_idM := (f.app m) idM
  have hg : Function.Surjective (g.app m) :=
    (ModuleCat.epi_iff_surjective (g.app m)).mp (hG i)
  let adj := Adjunction.ofIsRightAdjoint (forget (ModuleCat R))
  choose f'_idM hf'_idM using (hg fm_idM)
  refine ⟨?_, ?_⟩
  · refine ⟨?_, ?_⟩
    · intro X
      exact (adj.homEquiv
        (m ⟶ X) (G.obj X)).symm
        (TypeCat.ofHom fun fm ↦  G.map fm f'_idM)
    · intro X Y h
      apply (Adjunction.ofIsRightAdjoint
        (forget (ModuleCat R))).homEquiv_naturality_right_square
      ext fm
      simp
  · apply NatTrans.ext
    funext X
    simp only [NatTrans.comp_app]
    apply (adj.homEquiv (m ⟶ X) (G'.obj X)).injective
    change (adj.homEquiv (m ⟶ X) (G'.obj X))
        ((adj.homEquiv (m ⟶ X) (G.obj X)).symm
          (TypeCat.ofHom fun fm ↦ G.map fm f'_idM) ≫ g.app X) = _
    rw [adj.homEquiv_naturality_right]
    simp only [Equiv.apply_symm_apply]
    ext fm
    change g.app X (G.map fm f'_idM) =
      f.app X (adj.unit.app (m ⟶ X) fm)
    simp only [Functor.id_obj]
    rw [NatTrans.naturality_apply, hf'_idM]
    let q : (m ⟶ m) ⟶ (m ⟶ X) := TypeCat.ofHom fun k ↦ k ≫ fm
    have hunit := ConcreteCategory.congr_hom (adj.unit.naturality q) (𝟙 m)
    change adj.unit.app (m ⟶ X) (q (𝟙 m)) =
      FreeModule.map q (adj.unit.app (m ⟶ m) (𝟙 m)) at hunit
    have hf := ConcreteCategory.congr_hom (f.naturality fm) idM
    change f.app X (FreeModule.map q idM) = G'.map fm fm_idM at hf
    rw [← hf, ← hunit]
    simp only [q, TypeCat.ofHom_apply, Category.id_comp]
    rfl



lemma ShortComplexProjectiveLift {F G G' : (C ⥤ ModuleCat R)}
  (hF : ModelFree' P F) (β : G ⟶ G') (hG : EpiOnModels' P β) (α : F ⟶ G') :
    ∃ γ : F ⟶ G, γ  ≫ β = α := by
  let Q : P.FullSubcategory → (C ⥤ ModuleCat R) :=
    fun i => Hom[i.obj |-] ⋙ FreeModule
  let αi (i : P.FullSubcategory) : Q i ⟶ G' :=
    Limits.Sigma.ι Q i ≫ hF.iso.inv ≫ α
  let liftExists (i : P.FullSubcategory) :=
    ShortComplexProjectiveLift' (P := P) β hG (αi i)
  let γi (i : P.FullSubcategory) := Classical.choose (liftExists i)
  have hγi (i : P.FullSubcategory) : γi i ≫ β = αi i :=
    Classical.choose_spec (liftExists i)
  refine ⟨hF.iso.hom ≫ Limits.Sigma.desc γi, ?_⟩
  simp only [Category.assoc]
  rw [← cancel_epi hF.iso.inv]
  simp only [Iso.inv_hom_id_assoc]
  apply Limits.Sigma.hom_ext
  intro i
  rw [Limits.Sigma.ι_desc_assoc, hγi]



lemma ProjectiveLift {F G G' : (C ⥤ ModuleCat R)} {M : ModelObjects (C := C)}
  (hF : ModelFree M F) (β : G ⟶ G') (hG : EpiOnModels β M) (α : F ⟶ G') :
    ∃ γ : F ⟶ G, γ  ≫ β = α := by
    let P : M.Index → (C ⥤ ModuleCat R) :=
      fun i => Hom[M.model i |-] ⋙ FreeModule
    let αi (i : M.Index) : P i ⟶ G' :=
      Limits.Sigma.ι P i ≫ hF.iso.inv ≫ α
    let liftExists (i : M.Index) :=
      ProjectiveLift' β hG (αi i)
    let γi (i : M.Index) := Classical.choose (liftExists i)
    have hγi (i : M.Index) : γi i ≫ β = αi i :=
      Classical.choose_spec (liftExists i)
    refine ⟨hF.iso.hom ≫ Limits.Sigma.desc γi, ?_⟩
    simp only [Category.assoc]
    rw [← cancel_epi hF.iso.inv]
    simp only [Iso.inv_hom_id_assoc]
    apply Limits.Sigma.hom_ext
    intro i
    rw [Limits.Sigma.ι_desc_assoc, hγi]


lemma EpiOfAcyclicModels {F : FunctorComplex (C := C) (R := R)} {M : ModelObjects (C := C)}
  (hF : AcyclicOnModels M F) (i j : ℕ) (h : j + 1 = i := by omega) : EpiOnModels (F.d i j) M := by
  sorry

def ProjectiveOfShortComplex {F : FunctorComplex (C := C) (R := R)} {M : ModelObjects (C := C)}
  (hF : ComplexModelFree M F) (i : ℕ) : ModelFree M (F.cycles i) := by
  sorry


def ShortComplexIso (G : FunctorComplex ( C := C) (R := R)) (i : ℕ) : (G.sc (i)).X₁ ≅ G.X (i + 1) :=
  G.XIsoOfEq (by simp)


theorem ShortComplexAcyclicModelsLift
    {F G : ShortComplex (C ⥤ ModuleCat R)}
    (hF : ShortComplexModelFree P F)
    (hG : ShortComplexAcyclicOnModels P G)
    (ψ :
    (ShortComplex.homologyFunctor (C ⥤ ModuleCat.{w} R)).obj F ⟶
      (ShortComplex.homologyFunctor (C ⥤ ModuleCat.{w} R)).obj G) :
    ∃ α : F ⟶ G,
      (ShortComplex.homologyFunctor (C ⥤ ModuleCat.{w} R)).map α = ψ :=
  by sorry


/--
Basis version, existence: a natural map on zeroth homology lifts to a natural
chain map.
-/
theorem basis_acyclic_models_lift
    {M : ModelObjects (C := C)}
    {F : FunctorComplex (C := C) (R := R)}
    {G : FunctorComplex (C := C) (R := R)}
    (hF : ComplexModelFree M F)
    (hG : AcyclicOnModels M G)
    (φ :
      (HomologicalComplex.homologyFunctor
          (C ⥤ ModuleCat R) (ComplexShape.down ℕ) 0).obj F ⟶
        (HomologicalComplex.homologyFunctor
          (C ⥤ ModuleCat R) (ComplexShape.down ℕ) 0).obj G) :
    ∃ α : F ⟶ G,
      (HomologicalComplex.homologyFunctor
          (C ⥤ ModuleCat R) (ComplexShape.down ℕ) 0).map α = φ := by
  let πF : F.X 0 ⟶ F.homology 0 :=
    F.cycles₀Iso.inv ≫ F.homologyπ 0
  let πG : G.X 0 ⟶ G.homology 0 :=
    G.cycles₀Iso.inv ≫ G.homologyπ 0
  have hπG : EpiOnModels πG M := fun i => by
    dsimp only [πG]
    infer_instance
  let lift₀ := ProjectiveLift (hF 0) πG hπG (πF ≫ φ)
  let α₀ : F.X 0 ⟶ G.X 0 := Classical.choose lift₀
  have hα₀ : α₀ ≫ πG = πF ≫ φ := Classical.choose_spec lift₀
  let α₁Data :
      Σ' α₁ : F.X 1 ⟶ G.X 1,
        α₁ ≫ G.d 1 0 = F.d 1 0 ≫ α₀ := by
    let := ProjectiveLift (hF 1) (G.d 1 0) (EpiOfAcyclicModels hG 1 0) ((F.d 1 0) ≫ α₀)
    refine ⟨Classical.choose this, Classical.choose_spec this⟩
  let succData :
      ∀ (n : ℕ)
        (p :
          Σ' (αn : F.X n ⟶ G.X n) (αn₁ : F.X (n + 1) ⟶ G.X (n + 1)),
            αn₁ ≫ G.d (n + 1) n = F.d (n + 1) n ≫ αn),
        Σ' αn₂ : F.X (n + 2) ⟶ G.X (n + 2),
          αn₂ ≫ G.d (n + 2) (n + 1) =
            F.d (n + 2) (n + 1) ≫ p.2.1 := by
    rintro n ⟨fn, fn1, hfn⟩
    refine ⟨?_, ?_⟩
    ·
      refine (F.toCycles (n + 2) (n + 1)) ≫ ?_
      #check ((G.sc (n + 1)).toCycles)
      -- (HomologicalComplex.sc G (n + 1)).X₁ ⟶ (HomologicalComplex.sc G (n + 1)).cycles
      #check fun i ↦ (((HomologicalComplex.asFunctor G).obj (M.model i)).sc (n + 1)).toCycles
      --  (((HomologicalComplex.asFunctor G).obj (M.model i)).sc (n + 1)).X₁ ⟶ (((HomologicalComplex.asFunctor G).obj (M.model i)).sc (n + 1)).cycles
      refine Classical.choose <|
        ProjectiveLift (ProjectiveOfShortComplex hF (n + 1))
        (G.toCycles (n + 2)  (n + 1))
        (?_) ?_
      · -- TODO: Make (On Models) like subcategory...,
        -- then epi f ≫ g  -> g is mono -> f is epi
        intro i
        #check G.toCycles
        have := (hG i n)
        have := (hG i (n + 1) (by omega)).epi_toCycles
        -- dsimp [ShortComplex.toCycles] at this
        dsimp [HomologicalComplex.toCycles, HomologicalComplex.liftCycles]
        sorry
      exact (G.cyclesIsKernel (n + 1) n (by simp)).lift
        (KernelFork.ofι (F.iCycles (n + 1) ≫ fn1) (by
          simp only [Category.assoc, hfn,
            HomologicalComplex.iCycles_d_assoc, zero_comp]))
    · -- `p.2.2` is the commutative square in degrees `n + 1` and `n`;
      -- use it to construct the component in degree `n + 2`.
      simp [Classical.choose_spec]
      sorry
  let α : F ⟶ G :=
    ChainComplex.mkHom F G α₀ α₁Data.1 α₁Data.2 succData
  refine ⟨α, ?_⟩
  -- The degree-zero compatibility `hα₀` identifies the induced map with `φ`.
  -- simp [α, ChainComplex.mkHom]

  change HomologicalComplex.homologyMap α 0 = φ
  rw [← cancel_epi πF]
  erw [← hα₀]
  dsimp [πF, πG]
  rw [Category.assoc, HomologicalComplex.homologyπ_naturality]
  have hcycles :
      F.cycles₀Iso.inv ≫ HomologicalComplex.cyclesMap α 0 =
        α₀ ≫ G.cycles₀Iso.inv := by
    rw [← cancel_mono (G.iCycles 0)]
    simpa only [Category.assoc, HomologicalComplex.cyclesMap_i,
      HomologicalComplex.iCyclesIso_inv_hom_id_assoc,
      HomologicalComplex.iCyclesIso_inv_hom_id,
      Category.id_comp, Category.comp_id, α, ChainComplex.mkHom_f_0]
  simpa only [Category.assoc] using
    congrArg (fun k => k ≫ G.homologyπ 0) hcycles



-- /--
-- Basis version, uniqueness: natural chain maps inducing the same map on
-- zeroth homology are naturally chain-homotopic.
-- -/
-- theorem basis_acyclic_models_unique
--     {F : FunctorComplex (C := C) (R := R)}
--     (b : ComplexModelFree F)
--     (G : FunctorComplex (C := C) (R := R))
--     (hG : AcyclicOnModels b G)
--     (α β : F ⟶ G)
--     (h₀ :
--       (HomologicalComplex.homologyFunctor
--           (C ⥤ ModuleCat R) (ComplexShape.down ℕ) 0).map α =
--         (HomologicalComplex.homologyFunctor
--           (C ⥤ ModuleCat R) (ComplexShape.down ℕ) 0).map β) :
--     Nonempty (Homotopy α β) := by
--   sorry

end BasisVersion

-- /-! ## 2. A categorical, relative-projective formulation -/

-- section CategoricalVersion

-- variable {A : Type u} [Category.{v} A] [Preadditive A]
--   [HasZeroObject A]

-- /-- A specified class of objects which play the role of models/projectives. -/
-- structure ProjectiveClass (A : Type u) [Category.{v} A] where
--   objects : Set A

-- /-- A nonnegative chain complex equipped with an augmentation. -/
-- structure AugmentedComplex (A : Type u) [Category.{v} A]
--     [Preadditive A] [HasZeroObject A] where
--   complex : ChainComplex A ℕ
--   augmentationObject : A
--   augmentation : complex.X 0 ⟶ augmentationObject
--   d_comp_augmentation : complex.d 1 0 ≫ augmentation = 0

-- /--
-- `K` is exact when tested by maps from the objects in `P`.

-- The first clause says that maps to the augmentation object lift to degree
-- zero.  The remaining clauses say exactness at degree zero and in every
-- positive degree: every cycle detected from a model is a boundary.
-- -/
-- def ProjectiveClass.IsExact (P : ProjectiveClass A)
--     (K : AugmentedComplex A) : Prop :=
--   (∀ Q, Q ∈ P.objects →
--       Function.Surjective
--         (fun f : Q ⟶ K.complex.X 0 => f ≫ K.augmentation)) ∧
--   (∀ Q, Q ∈ P.objects → ∀ f : Q ⟶ K.complex.X 0,
--       f ≫ K.augmentation = 0 →
--       ∃ g : Q ⟶ K.complex.X 1,
--         g ≫ K.complex.d 1 0 = f) ∧
--   (∀ Q, Q ∈ P.objects → ∀ n (f : Q ⟶ K.complex.X (n + 1)),
--       f ≫ K.complex.d (n + 1) n = 0 →
--       ∃ g : Q ⟶ K.complex.X (n + 2),
--         g ≫ K.complex.d (n + 2) (n + 1) = f)

-- /-- A chain map compatible with a specified map of augmentation objects. -/
-- def LiftsAugmentation (K L : AugmentedComplex A)
--     (f : K.augmentationObject ⟶ L.augmentationObject)
--     (α : K.complex ⟶ L.complex) : Prop :=
--   α.f 0 ≫ L.augmentation = K.augmentation ≫ f

-- /--
-- Categorical acyclic models, existence.

-- The terms of the source complex belong to the chosen projective class, and
-- the target augmented complex is exact when tested against that class.
-- -/
-- theorem categorical_acyclic_models_lift
--     (P : ProjectiveClass A)
--     (K L : AugmentedComplex A)
--     (hK : ∀ n, K.complex.X n ∈ P.objects)
--     (hL : P.IsExact L)
--     (f : K.augmentationObject ⟶ L.augmentationObject) :
--     ∃ α : K.complex ⟶ L.complex, LiftsAugmentation K L f α := by
--   sorry

-- /--
-- Categorical acyclic models, uniqueness up to chain homotopy.
-- -/
-- theorem categorical_acyclic_models_unique
--     (P : ProjectiveClass A)
--     (K L : AugmentedComplex A)
--     (hK : ∀ n, K.complex.X n ∈ P.objects)
--     (hL : P.IsExact L)
--     (f : K.augmentationObject ⟶ L.augmentationObject)
--     (α β : K.complex ⟶ L.complex)
--     (hα : LiftsAugmentation K L f α)
--     (hβ : LiftsAugmentation K L f β) :
--     Nonempty (Homotopy α β) := by
--   sorry

-- end CategoricalVersion

end AcyclicModels
