import Mathlib.CategoryTheory.Monoidal.Category
import Mathlib.CategoryTheory.Quotient

/-!
# Cubical sites

This file formalizes the cubical sites of Grandis–Mauri, *Cubical sets and their
site* (TAC 11, 2003). Following the paper, we work with three nested categories
whose objects are the elementary cubes `2ⁿ`:

* `I` — the restricted cubical site, generated by faces `δ` and degeneracies `ε`;
* `J` — the intermediate site, adding connections `γ`;
* `K` — the extended site, adding the interchange `σ`.

The main definition will be the extended cubical site `K`, characterized (Theorem
8.2 of the paper) as the category generated by faces, degeneracies, connections
and interchanges subject to the extended cocubical relations.
-/

open CategoryTheory

universe w v u

namespace HomologyLean.InfinityCategories

namespace Cubical

/-- Dimensions of elementary cubes are natural numbers. -/
abbrev Dim := ℕ

end Cubical

end HomologyLean.InfinityCategories
