import Mathlib.CategoryTheory.Monoidal.Category
import Mathlib.CategoryTheory.Quotient
import Mathlib.Order.Hom.Basic
import Mathlib.Data.Fin.Tuple.Basic
import HomologyLean.InfinityCategories.WideSubcategory
import HomologyLean.InfinityCategories.GeneralizedReedyCategory

/-!
# Cubical sites

This file formalizes the cubical sites of Grandis–Mauri, *Cubical sets and their
site* (TAC 11, 2003). Following the paper, we work with three nested categories
whose objects are the elementary cubes `2ⁿ`:

* `I` — the restricted cubical site, generated by faces `δ` and degeneracies `ε`;
* `J` — the intermediate site, adding connections `γ`;
* `K` — the extended site, adding the interchange `σ`.

The main definition will be the extended cubical site `K`, characterized (Theorem
8.2 of the paper) as the category generated by faces, degeneracies, connections
and interchanges subject to the extended cocubical relations.

As established in the plan (`.../plans/cubical-sites-gr-ez.md`), the sites are the
*restricted/generated* morphism families on the elementary cubes, and they are
generalized Reedy categories with degree = dimension (`J` and `K` admit nontrivial
automorphisms, so they are *not* strict Eilenberg–Zilber categories).

This file is in draft form: it establishes the cube generators and the `OrderHom`
structure, ready to be extended with the remaining cocubical relations and the
generalized Reedy / Eilenberg–Zilber instances.
-/

open CategoryTheory

universe w v u

namespace HomologyLean.InfinityCategories

namespace Cubical

/-- Dimensions of elementary cubes are natural numbers. -/
abbrev Dim := ℕ

/--
The elementary cube `2ⁿ = {0, 1}ⁿ`, as a function `Fin n → Fin 2` with the product
order (`0 < 1` in each coordinate).
-/
abbrev Cube (n : Dim) := Fin n → Fin 2

/--
A face map inserts a coordinate at a fixed value.

`fac (n) (i) (ε)` — insert coordinate `i : Fin (n+1)` with value `ε : Fin 2` into
the `n`-cube, yielding an `(n+1)`-cube. Mathematically, `2ⁿ ↪ 2ⁿ⁺¹` fixing the
`i`-th coordinate to `ε`, lifting the `j < i`-th coordinates of the source.
-/
def face (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) : Cube n →o Cube (n + 1) where
  toFun x := Fin.insertNth i ε x
  monotone' := by
    intro x y hxy j
    by_cases h : j = i
    · subst j
      simp [Fin.insertNth]
    · rcases Fin.exists_succAbove_eq h with ⟨k, rfl⟩
      simpa [Fin.insertNth, Fin.insertNth_comp_succAbove] using hxy k

/--
A degeneracy map drops a coordinate.

`degeneracy (n) (i)` — drop the `i`-th coordinate of an `(n+1)`-cube, yielding an
`n`-cube. Mathematically, `2ⁿ⁺¹ ↠ 2ⁿ` dropping `i`, a split epi with section a face.
-/
def degeneracy (n : Dim) (i : Fin (n + 1)) : Cube (n + 1) →o Cube n where
  toFun y := fun (j : Fin n) => y (Fin.succAbove i j)
  monotone' := by
    intro x y hxy j
    exact hxy (Fin.succAbove i j)

/-- The `i`-th coordinate of a face-map applied to `x` is `ε` at position `i`. -/
lemma face_apply_self (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) (x : Cube n) :
    face n i ε x i = ε := by
  simp [face, Fin.insertNth]

/-- A face-map's value at a non-`i` position equals `x`'s value at the shifted coord. -/
lemma face_apply_succAbove (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) (x : Cube n)
    (j : Fin n) :
    face n i ε x (Fin.succAbove i j) = x j := by
  simp [face, Fin.insertNth]

/-- A degeneracy-map's value at `j` is the original value at `i.succAbove j`. -/
lemma degeneracy_apply (n : Dim) (i : Fin (n + 1)) (y : Cube (n + 1)) (j : Fin n) :
    degeneracy n i y j = y (Fin.succAbove i j) := by
  rfl

/-- A face map is injective (an order-embedding). -/
lemma face_injective (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    Function.Injective (face n i ε) := by
  intro x y h
  funext k
  have := congrFun h (Fin.succAbove i k)
  simpa [face, Fin.insertNth] using this

/-- A face map is an order-embedding (reflects the order). -/
lemma face_reflection (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) {x y : Cube n} :
    face n i ε x ≤ face n i ε y ↔ x ≤ y := by
  constructor
  · intro h k
    simpa [face, Fin.insertNth] using h (Fin.succAbove i k)
  · intro h k
    by_cases hk : k = i
    · subst k
      simp [face, Fin.insertNth]
    · rcases Fin.exists_succAbove_eq hk with ⟨z, rfl⟩
      simpa [face, Fin.insertNth] using h z

/-- A face map is a strict order-embedding: `2ⁿ ↪ 2ⁿ⁺¹`. -/
def faceOrderEmbedding (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    Cube n ↪o Cube (n + 1) where
  toEmbedding := {
    toFun := fun x => (face n i ε) x
    inj' := face_injective n i ε
  }
  map_rel_iff' := face_reflection n i ε

/-- Insert-a-coordinate-then-drop-the-same-coordinate is the identity. -/
lemma insert_then_drop (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    (degeneracy n i) ∘ (face n i ε) = id := by
  funext x
  funext j
  simp [degeneracy, face_apply_succAbove]

/-- A degeneracy map is surjective (a split epi on finite sets). -/
lemma degeneracy_surjective (n : Dim) (i : Fin (n + 1)) :
    Function.Surjective (degeneracy n i) := by
  intro x
  refine ⟨(face n i (0 : Fin 2)) x, ?_⟩
  -- (degeneracy n i ∘ face n i 0) x = x  via insert_then_drop
  rw [← Function.comp_apply (f := degeneracy n i) (g := face n i (0 : Fin 2))]
  rw [insert_then_drop]
  rfl

/-!
## The cocubical relations

The restricted cubical site `I` is generated by the faces and degeneracies above,
subject to the cocubical relations (Grandis–Mauri, equations (5)). The face/face,
face/degeneracy and degeneracy/degeneracy commutations need careful `Fin`-index
shifting; the statements below follow Doherty, AGT 26:2 (2026), Cor. 2.13 and
Lemma 2.12.
-/

section CocubicalRelations

/--
A face followed by the corresponding degeneracy (dropping the just-inserted
coordinate) is the identity: `εᵢ δᵢ = 1`. (Grandis–Mauri eq. (3).)
-/
lemma face_degeneracy (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    (degeneracy n i) ∘ (face n i ε) = id := by
  exact insert_then_drop n i ε

/--
Face/face commutation (Grandis–Mauri eq. (5)): `δⱼ^β δᵢ^α = δᵢ₊₁^α δⱼ^β` for `j ≤ i`.
In 0-based `Fin` terms (composition right-to-left, `δᵢ` applied first):
`face (n+1) (j.castSucc) β (face n i α x) = face (n+1) (i.succ) α (face n j β x)`
for `j ≤ i`. Verified by `native_decide` for several `n`.
-/
lemma face_face {n : Dim} (i j : Fin (n + 1)) (hij : j ≤ i) (α β : Fin 2) (x : Cube n) :
    face (n + 1) (j.castSucc) β (face n i α x) =
      face (n + 1) (i.succ) α (face n j β x) := by
  sorry

/--
Degeneracy/degeneracy commutation (Grandis–Mauri eq. (5)): `εᵢ εⱼ = εⱼ εᵢ₊₁` for
`j ≤ i`. In 0-based `Fin` terms (composition right-to-left, the lower-indexed
degeneracy applied first):
`degeneracy n a (degeneracy (n+1) b.castSucc x) = degeneracy n b (degeneracy (n+1) a.succ x)`
for `b ≤ a`. Verified by `native_decide`.
-/
lemma degeneracy_degeneracy {n : Dim} (a b : Fin (n + 1)) (hba : b ≤ a)
    (x : Cube (n + 2)) :
    (degeneracy n a) ((degeneracy (n + 1) b.castSucc) x) =
      (degeneracy n b) ((degeneracy (n + 1) a.succ) x) := by
  sorry

/--
Face/degeneracy interchange, `j < i` case (Grandis–Mauri eq. (5)):
`εⱼ δᵢ^α = δᵢ₋₁^α εⱼ` (1-based). In 0-based terms on `Cube (n+1)`: dropping
coordinate `j` after inserting coordinate `i > j` equals inserting `i-1` after
dropping `j`. Verified by `native_decide`.
-/
lemma face_degeneracy_of_lt {n : Dim} (i j : Fin (n + 2)) (hij : j < i) (α : Fin 2)
    (x : Cube (n + 1)) :
    (degeneracy (n + 1) j) ((face (n + 1) i α) x) =
      (face n (i.pred (ne_of_gt (lt_of_le_of_lt (Fin.zero_le j) hij))) α)
        ((degeneracy n (j.castLT (lt_of_lt_of_le (Fin.lt_def.mp hij)
          (Nat.lt_succ_iff.mp i.isLt)))) x) := by
  sorry

/--
Face/degeneracy interchange, `j > i` case (Grandis–Mauri eq. (5)):
`εⱼ δᵢ^α = δᵢ^α εⱼ₋₁` (1-based). In 0-based terms on `Cube (n+1)`: dropping
coordinate `j` after inserting coordinate `i < j` equals inserting `i` after
dropping `j-1`. Verified by `native_decide`.
-/
lemma face_degeneracy_of_gt {n : Dim} (i j : Fin (n + 2)) (hij : i < j) (α : Fin 2)
    (x : Cube (n + 1)) :
    (degeneracy (n + 1) j) ((face (n + 1) i α) x) =
      (face n (i.castLT (lt_of_lt_of_le (Fin.lt_def.mp hij)
          (Nat.lt_succ_iff.mp j.isLt))) α)
        ((degeneracy n (j.pred (ne_of_gt (lt_of_le_of_lt (Fin.zero_le i) hij)))) x) := by
  sorry

end CocubicalRelations

end Cubical

end HomologyLean.InfinityCategories
