import Mathlib.CategoryTheory.Monoidal.Category
import Mathlib.CategoryTheory.Quotient
import Mathlib.Order.Hom.Basic
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.BigOperators
import HomologyLean.InfinityCategories.WideSubcategory
import HomologyLean.InfinityCategories.GeneralizedReedyCategory

/-!
# Cubical sites

This file formalizes the cubical sites of Grandis–Mauri, *Cubical sets and their
site* (TAC 11, 2003). Following the paper, we work with three nested categories
whose objects are the elementary cubes `2ⁿ`:

* `I` — the restricted cubical site, generated by faces `δ` and degeneracies `ε`;
* `J` — the intermediate site, adding connections `γ`;
* `K` — the extended site, adding the interchange `σ`.

The main definition will be the extended cubical site `K`, characterized (Theorem
8.2 of the paper) as the category generated by faces, degeneracies, connections
and interchanges subject to the extended cocubical relations.

As established in the plan (`.../plans/cubical-sites-gr-ez.md`), the sites are the
*restricted/generated* morphism families on the elementary cubes, and they are
generalized Reedy categories with degree = dimension (`J` and `K` admit nontrivial
automorphisms, so they are *not* strict Eilenberg–Zilber categories).

This file is in draft form: it establishes the cube generators and the `OrderHom`
structure, ready to be extended with the remaining cocubical relations and the
generalized Reedy / Eilenberg–Zilber instances.
-/

open CategoryTheory

universe w v u

namespace HomologyLean.InfinityCategories

namespace Cubical

/-- Dimensions of elementary cubes are natural numbers. -/
abbrev Dim := ℕ

/--
The elementary cube `2ⁿ = {0, 1}ⁿ`, as a function `Fin n → Fin 2` with the product
order (`0 < 1` in each coordinate).
-/
abbrev Cube (n : Dim) := Fin n → Fin 2

/--
A face map inserts a coordinate at a fixed value.

`fac (n) (i) (ε)` — insert coordinate `i : Fin (n+1)` with value `ε : Fin 2` into
the `n`-cube, yielding an `(n+1)`-cube. Mathematically, `2ⁿ ↪ 2ⁿ⁺¹` fixing the
`i`-th coordinate to `ε`, lifting the `j < i`-th coordinates of the source.
-/
def face (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) : Cube n →o Cube (n + 1) where
  toFun x := Fin.insertNth i ε x
  monotone' := by
    intro x y hxy j
    by_cases h : j = i
    · subst j
      simp [Fin.insertNth]
    · rcases Fin.exists_succAbove_eq h with ⟨k, rfl⟩
      simpa [Fin.insertNth, Fin.insertNth_comp_succAbove] using hxy k

/--
A degeneracy map drops a coordinate.

`degeneracy (n) (i)` — drop the `i`-th coordinate of an `(n+1)`-cube, yielding an
`n`-cube. Mathematically, `2ⁿ⁺¹ ↠ 2ⁿ` dropping `i`, a split epi with section a face.
-/
def degeneracy (n : Dim) (i : Fin (n + 1)) : Cube (n + 1) →o Cube n where
  toFun y := fun (j : Fin n) => y (Fin.succAbove i j)
  monotone' := by
    intro x y hxy j
    exact hxy (Fin.succAbove i j)

/-- The `i`-th coordinate of a face-map applied to `x` is `ε` at position `i`. -/
lemma face_apply_self (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) (x : Cube n) :
    face n i ε x i = ε := by
  simp [face, Fin.insertNth]

/-- A face-map's value at a non-`i` position equals `x`'s value at the shifted coord. -/
lemma face_apply_succAbove (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) (x : Cube n)
    (j : Fin n) :
    face n i ε x (Fin.succAbove i j) = x j := by
  simp [face, Fin.insertNth]

/-- A degeneracy-map's value at `j` is the original value at `i.succAbove j`. -/
lemma degeneracy_apply (n : Dim) (i : Fin (n + 1)) (y : Cube (n + 1)) (j : Fin n) :
    degeneracy n i y j = y (Fin.succAbove i j) := by
  rfl

/-- A face map is injective (an order-embedding). -/
lemma face_injective (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    Function.Injective (face n i ε) := by
  intro x y h
  funext k
  have := congrFun h (Fin.succAbove i k)
  simpa [face, Fin.insertNth] using this

/-- A face map is an order-embedding (reflects the order). -/
lemma face_reflection (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) {x y : Cube n} :
    face n i ε x ≤ face n i ε y ↔ x ≤ y := by
  constructor
  · intro h k
    simpa [face, Fin.insertNth] using h (Fin.succAbove i k)
  · intro h k
    by_cases hk : k = i
    · subst k
      simp [face, Fin.insertNth]
    · rcases Fin.exists_succAbove_eq hk with ⟨z, rfl⟩
      simpa [face, Fin.insertNth] using h z

/-- A face map is a strict order-embedding: `2ⁿ ↪ 2ⁿ⁺¹`. -/
def faceOrderEmbedding (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    Cube n ↪o Cube (n + 1) where
  toEmbedding := {
    toFun := fun x => (face n i ε) x
    inj' := face_injective n i ε
  }
  map_rel_iff' := face_reflection n i ε

/-- A face followed by the corresponding degeneracy (dropping the just-inserted
coordinate) is the identity: `εᵢ δᵢ = 1`. (Grandis–Mauri eq. (3).) -/
lemma insert_then_drop (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
    (degeneracy n i) ∘ (face n i ε) = id := by
  funext x
  funext j
  simp [degeneracy, face_apply_succAbove]

/-- A degeneracy map is surjective (a split epi on finite sets). -/
lemma degeneracy_surjective (n : Dim) (i : Fin (n + 1)) :
    Function.Surjective (degeneracy n i) := by
  intro x
  refine ⟨(face n i (0 : Fin 2)) x, ?_⟩
  -- (degeneracy n i ∘ face n i 0) x = x  via insert_then_drop
  rw [← Function.comp_apply (f := degeneracy n i) (g := face n i (0 : Fin 2))]
  rw [insert_then_drop]
  rfl

/-!
## The cocubical relations

The restricted cubical site `I` is generated by the faces and degeneracies above,
subject to the cocubical relations (Grandis–Mauri, equations (5)). The face/face,
face/degeneracy and degeneracy/degeneracy commutations need careful `Fin`-index
shifting; the statements below follow Doherty, AGT 26:2 (2026), Cor. 2.13 and
Lemma 2.12.
-/

section CocubicalRelations

/-- Double insertion commutation on the shifted indices:
`i.succAbove (j.succAbove k) = j.castSucc.succAbove (i.succAbove k)` for `j ≤ i`. -/
lemma succAbove_succAbove_comm {n : ℕ} (i j : Fin (n + 1)) (hij : j ≤ i) (k : Fin n) :
    i.succ.succAbove (j.succAbove k) = j.castSucc.succAbove (i.succAbove k) := by
  apply Fin.ext
  dsimp only [Fin.succAbove]
  rcases i with ⟨i, hi⟩; rcases j with ⟨j, hj⟩; rcases k with ⟨k, hk⟩
  split_ifs <;> simp at * <;> omega

/--
Face/face commutation (Grandis–Mauri eq. (5)): `δⱼ^β δᵢ^α = δᵢ₊₁^α δⱼ^β` for `j ≤ i`.
In 0-based `Fin` terms (composition right-to-left, `δᵢ` applied first):
`face (n+1) (j.castSucc) β (face n i α x) = face (n+1) (i.succ) α (face n j β x)`
for `j ≤ i`. Verified by `native_decide` for several `n`.
-/
lemma face_face {n : Dim} (i j : Fin (n + 1)) (hij : j ≤ i) (α β : Fin 2) (x : Cube n) :
    face (n + 1) (j.castSucc) β (face n i α x) =
      face (n + 1) (i.succ) α (face n j β x) := by
  funext k
  -- Case-split on whether `k` is the `j.castSucc`-hole, then (if not) on whether its
  -- preimage is the `i`-hole. Each case rewrites the index to `succAbove`-/`self`-shape
  -- and finishes with `face_apply_self`/`face_apply_succAbove`.
  by_cases hjk : k = j.castSucc
  · subst k
    -- RHS index `j.castSucc` is the `i.succ`-image of `j`, so the outer insertion is
    -- peeled to the inner one, which returns `β` at position `j`.
    rw [face_apply_self, (Fin.succAbove_succ_of_le i j hij).symm, face_apply_succAbove,
      face_apply_self]
  rcases Fin.exists_succAbove_eq hjk with ⟨a, rfl⟩
  rw [face_apply_succAbove]
  by_cases hai : a = i
  · subst a
    -- RHS index `j.castSucc.succAbove i = i.succ` (since `j ≤ i`), the `i.succ`-hole.
    rw [face_apply_self, Fin.succAbove_castSucc_of_le j i hij, face_apply_self]
  rcases Fin.exists_succAbove_eq hai with ⟨b, rfl⟩
  rw [face_apply_succAbove, (succAbove_succAbove_comm i j hij b).symm,
    face_apply_succAbove, face_apply_succAbove]
lemma degeneracy_degeneracy {n : Dim} (a b : Fin (n + 1)) (hba : b ≤ a)
    (x : Cube (n + 2)) :
    (degeneracy n a) ((degeneracy (n + 1) b.castSucc) x) =
      (degeneracy n b) ((degeneracy (n + 1) a.succ) x) := by
  -- Both sides are `x` at a double-`succAbove` index; `succAbove_succAbove_comm`
  -- equates the two indices.
  funext j
  simp only [degeneracy_apply, succAbove_succAbove_comm a b hba]

/--
Face/degeneracy interchange, `j < i` case (Grandis–Mauri eq. (5)):
`εⱼ δᵢ^α = δᵢ₋₁^α εⱼ` (1-based). In 0-based terms on `Cube (n+1)`: dropping
coordinate `j` after inserting coordinate `i > j` equals inserting `i-1` after
dropping `j`. Verified by `native_decide`.
-/
lemma face_degeneracy_of_lt {n : Dim} (i j : Fin (n + 2)) (hij : j < i) (α : Fin 2)
    (x : Cube (n + 1)) :
    (degeneracy (n + 1) j) ((face (n + 1) i α) x) =
      (face n (i.pred (ne_of_gt (lt_of_le_of_lt (Fin.zero_le j) hij))) α)
        ((degeneracy n (j.castLT (lt_of_lt_of_le (Fin.lt_def.mp hij)
          (Nat.lt_succ_iff.mp i.isLt)))) x) := by
  funext k
  -- Case-split on whether `k` is the `i.pred`-hole; if not, write it as
  -- `(i.pred _).succAbove b` and commute the two deletions via
  -- `succAbove_succAbove_comm` instantiated at `(i.pred _, j.castLT _)`.
  by_cases hk : k = i.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt j.zero_le hij))
  · subst k
    -- LHS index `j.succAbove (i.pred _) = i` (since `j < i`): both faces hit their hole.
    rw [degeneracy_apply, Fin.succAbove_pred_of_lt j i hij, face_apply_self, face_apply_self]
  rcases Fin.exists_succAbove_eq hk with ⟨b, rfl⟩
  have hle : j.castLT (hij.trans_le (Fin.le_last i)) ≤
      i.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt j.zero_le hij)) := by
    have h := Fin.lt_def.mp hij
    simp only [Fin.le_def, Fin.val_castLT, Fin.val_pred]
    omega
  have key : j.succAbove
        ((i.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt j.zero_le hij))).succAbove b) =
      i.succAbove ((j.castLT (hij.trans_le (Fin.le_last i))).succAbove b) := by
    have h := succAbove_succAbove_comm
      (i.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt j.zero_le hij)))
      (j.castLT (hij.trans_le (Fin.le_last i))) hle b
    rw [Fin.succ_pred, Fin.castSucc_castLT] at h
    exact h.symm
  rw [face_apply_succAbove, degeneracy_apply, degeneracy_apply, key, face_apply_succAbove]
  rfl

/--
Face/degeneracy interchange, `j > i` case (Grandis–Mauri eq. (5)):
`εⱼ δᵢ^α = δᵢ^α εⱼ₋₁` (1-based). In 0-based terms on `Cube (n+1)`: dropping
coordinate `j` after inserting coordinate `i < j` equals inserting `i` after
dropping `j-1`. Verified by `native_decide`.
-/
lemma face_degeneracy_of_gt {n : Dim} (i j : Fin (n + 2)) (hij : i < j) (α : Fin 2)
    (x : Cube (n + 1)) :
    (degeneracy (n + 1) j) ((face (n + 1) i α) x) =
      (face n (i.castLT (lt_of_lt_of_le (Fin.lt_def.mp hij)
          (Nat.lt_succ_iff.mp j.isLt))) α)
        ((degeneracy n (j.pred (ne_of_gt (lt_of_le_of_lt (Fin.zero_le i) hij)))) x) := by
  -- The goal's `i.castLT _` is definitionally `i.castPred _` (both are `⟨i, _⟩`),
  -- but `Fin.succAbove_castPred_of_lt` needs the latter syntactically.
  change (degeneracy (n + 1) j) ((face (n + 1) i α) x) =
    (face n (i.castPred (Fin.ne_of_lt (Nat.lt_of_lt_of_le hij (Fin.le_last j)))) α)
      ((degeneracy n (j.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt i.zero_le hij)))) x)
  funext k
  -- Case-split on whether `k` is the `i.castPred`-hole; if not, write it as
  -- `(i.castPred _).succAbove b` and commute the two deletions via
  -- `succAbove_succAbove_comm` instantiated at `(j.pred _, i.castPred _)`.
  by_cases hk : k = i.castPred (Fin.ne_of_lt (Nat.lt_of_lt_of_le hij (Fin.le_last j)))
  · subst k
    -- LHS index `j.succAbove (i.castPred _) = i` (since `i < j`): both faces hit their hole.
    rw [degeneracy_apply, Fin.succAbove_castPred_of_lt j i hij, face_apply_self,
      face_apply_self]
  rcases Fin.exists_succAbove_eq hk with ⟨b, rfl⟩
  have hle : i.castPred (Fin.ne_of_lt (Nat.lt_of_lt_of_le hij (Fin.le_last j))) ≤
      j.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt i.zero_le hij)) := by
    have h := Fin.lt_def.mp hij
    simp only [Fin.le_def, Fin.coe_castPred, Fin.val_pred]
    omega
  have key : j.succAbove
        ((i.castPred (Fin.ne_of_lt (Nat.lt_of_lt_of_le hij (Fin.le_last j)))).succAbove b) =
      i.succAbove ((j.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt i.zero_le hij))).succAbove b) := by
    have h := succAbove_succAbove_comm
      (j.pred (Fin.ne_of_gt (Fin.lt_of_le_of_lt i.zero_le hij)))
      (i.castPred (Fin.ne_of_lt (Nat.lt_of_lt_of_le hij (Fin.le_last j)))) hle b
    rw [Fin.succ_pred, Fin.castSucc_castPred] at h
    exact h
  rw [face_apply_succAbove, degeneracy_apply, degeneracy_apply, key, face_apply_succAbove]

end CocubicalRelations

/-!
## The cubical site as a category

The site has objects the dimensions `n : ℕ` (standing for the cube `2ⁿ`) and
morphisms the monotone maps `2ⁿ → 2ᵐ` **generated** by faces and degeneracies
(Grandis–Mauri, restricted site `I`). We model the generated family as an
inductive predicate on `OrderHom`s, so that a morphism of the site is an
order-hom *bundled with a proof* that it is generated. Two morphisms are equal
iff their underlying order-homs agree pointwise, so the cocubical relations
above become genuine equalities in the category (no quotient needed).
-/

section CubeSiteCategory

/--
The generated family of cube maps (restricted site `I`): the smallest class of
monotone maps containing the faces `δᵢᵉ : 2ⁿ → 2ⁿ⁺¹` and degeneracies
`εᵢ : 2ⁿ⁺¹ → 2ⁿ`, and closed under identity and composition.
-/
inductive IsGen : (n m : Dim) → (Cube n →o Cube m) → Prop
  /-- The identity is generated. -/
  | id (n : Dim) : IsGen n n (OrderHom.id)
  /-- Every face map is generated. -/
  | face (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) : IsGen n (n + 1) (face n i ε)
  /-- Every degeneracy is generated. -/
  | degeneracy (n : Dim) (i : Fin (n + 1)) : IsGen (n + 1) n (degeneracy n i)
  /-- The family is closed under composition (apply `f` first, then `g`). -/
  | comp {n m k : Dim} {f : Cube n →o Cube m} {g : Cube m →o Cube k} :
      IsGen n m f → IsGen m k g → IsGen n k (g.comp f)

/-- A morphism of the cubical site from the `n`-cube to the `m`-cube: a
monotone map `2ⁿ → 2ᵐ` generated by faces and degeneracies. -/
structure CubeHom (n m : Dim) where
  /-- The underlying monotone map `2ⁿ → 2ᵐ`. -/
  toOrderHom : Cube n →o Cube m
  /-- The underlying map is generated by faces and degeneracies. -/
  isGen : IsGen n m toOrderHom

namespace CubeHom

/-- Extensionality: two cube maps are equal if their underlying order-homs
agree. (Proof irrelevance discharges the `isGen` components.) -/
@[ext]
theorem ext {n m : Dim} {f g : CubeHom n m} (h : f.toOrderHom = g.toOrderHom) : f = g := by
  cases f; cases g; subst h; rfl

/-- The identity cube map. -/
def id (n : Dim) : CubeHom n n := ⟨OrderHom.id, .id n⟩

/-- Composition of cube maps (`f` first, then `g`), i.e. `f ≫ g`. -/
def comp {n m k : Dim} (f : CubeHom n m) (g : CubeHom m k) : CubeHom n k :=
  ⟨g.toOrderHom.comp f.toOrderHom, .comp f.isGen g.isGen⟩

@[simp] theorem id_toOrderHom (n : Dim) : (id n).toOrderHom = OrderHom.id := rfl

@[simp] theorem comp_toOrderHom {n m k : Dim} (f : CubeHom n m) (g : CubeHom m k) :
    (comp f g).toOrderHom = g.toOrderHom.comp f.toOrderHom := rfl

end CubeHom

/-- The cubical site (restricted site `I`): objects are dimensions `n : ℕ`,
morphisms `n ⟶ m` are the generated cube maps `2ⁿ → 2ᵐ`. -/
instance cubeSiteCategory : Category Dim where
  Hom := CubeHom
  id := CubeHom.id
  comp := CubeHom.comp
  id_comp _f := CubeHom.ext (OrderHom.id_comp _)
  comp_id _f := CubeHom.ext (OrderHom.comp_id _)
  assoc _f _g _h := CubeHom.ext (OrderHom.comp_assoc _ _ _)

/-- A face map bundled as a morphism of the restricted cubical site. -/
def faceHom (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) : n ⟶ n + 1 :=
  ⟨face n i ε, .face n i ε⟩

/-- A degeneracy map bundled as a morphism of the restricted cubical site. -/
def degeneracyHom (n : Dim) (i : Fin (n + 1)) : n + 1 ⟶ n :=
  ⟨degeneracy n i, .degeneracy n i⟩

/-- A morphism which is either an identity or a single face. -/
inductive IsFaceAtom : {n m : Dim} → (n ⟶ m) → Prop
  | id (n : Dim) : IsFaceAtom (𝟙 n)
  | face (n : Dim) (i : Fin (n + 1)) (ε : Fin 2) :
      IsFaceAtom (faceHom n i ε)

/-- A morphism composed entirely of face maps. -/
inductive IsFaceComposite : {n m : Dim} → (n ⟶ m) → Prop
  | atom {n m : Dim} {f : n ⟶ m} (hf : IsFaceAtom f) : IsFaceComposite f
  | comp {n m k : Dim} {f : n ⟶ m} {g : m ⟶ k}
      (hf : IsFaceComposite f) (hg : IsFaceComposite g) :
      IsFaceComposite (f ≫ g)

/-- A morphism composed entirely of degeneracy maps. -/
inductive IsDegeneracyComposite : {n m : Dim} → (n ⟶ m) → Prop
  | id (n : Dim) : IsDegeneracyComposite (𝟙 n)
  | degeneracy (n : Dim) (i : Fin (n + 1)) :
      IsDegeneracyComposite (degeneracyHom n i)
  | comp {n m k : Dim} {f : n ⟶ m} {g : m ⟶ k}
      (hf : IsDegeneracyComposite f) (hg : IsDegeneracyComposite g) :
      IsDegeneracyComposite (f ≫ g)

lemma IsFaceAtom.isComposite {n m : Dim} {f : n ⟶ m} (hf : IsFaceAtom f) :
    IsFaceComposite f :=
  .atom hf

lemma IsFaceComposite.injective {n m : Dim} {f : n ⟶ m}
    (hf : IsFaceComposite f) : Function.Injective ⇑f.toOrderHom := by
  induction hf with
  | atom hf =>
      cases hf with
      | id => exact fun _ _ h => h
      | face i ε => exact face_injective _ i ε
  | comp hf hg ihf ihg => exact ihg.comp ihf

/-- Every face composite has a retraction made from degeneracy maps. -/
lemma IsFaceComposite.hasRetraction {n m : Dim} {f : n ⟶ m}
    (hf : IsFaceComposite f) : ∃ r : m ⟶ n, f ≫ r = 𝟙 n := by
  induction hf with
  | atom hf =>
      cases hf with
      | id => exact ⟨𝟙 _, by simp⟩
      | face i α =>
          refine ⟨degeneracyHom _ i, ?_⟩
          apply CubeHom.ext
          apply OrderHom.ext
          funext x
          exact congrFun (insert_then_drop _ i α) x
  | @comp n m k f g hf hg ihf ihg =>
      obtain ⟨rf, hrf⟩ := ihf
      obtain ⟨rg, hrg⟩ := ihg
      refine ⟨rg ≫ rf, ?_⟩
      calc
        (f ≫ g) ≫ (rg ≫ rf) = f ≫ ((g ≫ rg) ≫ rf) := by
          simp only [Category.assoc]
        _ = f ≫ rf := by rw [hrg, Category.id_comp]
        _ = 𝟙 n := hrf

lemma IsDegeneracyComposite.surjective {n m : Dim} {f : n ⟶ m}
    (hf : IsDegeneracyComposite f) : Function.Surjective ⇑f.toOrderHom := by
  induction hf with
  | id n => exact fun x => ⟨x, rfl⟩
  | degeneracy n i => exact degeneracy_surjective n i
  | comp hf hg ihf ihg => exact ihg.comp ihf

/-- Every degeneracy composite has a section made from face maps. -/
lemma IsDegeneracyComposite.hasSection {n m : Dim} {f : n ⟶ m}
    (hf : IsDegeneracyComposite f) : ∃ s : m ⟶ n, s ≫ f = 𝟙 m := by
  induction hf with
  | id n => exact ⟨𝟙 n, by simp⟩
  | degeneracy n i =>
      refine ⟨faceHom n i 0, ?_⟩
      apply CubeHom.ext
      apply OrderHom.ext
      funext x
      exact congrFun (insert_then_drop n i 0) x
  | @comp n m k f g hf hg ihf ihg =>
      obtain ⟨sf, hsf⟩ := ihf
      obtain ⟨sg, hsg⟩ := ihg
      refine ⟨sg ≫ sf, ?_⟩
      calc
        (sg ≫ sf) ≫ (f ≫ g) = sg ≫ ((sf ≫ f) ≫ g) := by simp only [Category.assoc]
        _ = sg ≫ g := by rw [hsf, Category.id_comp]
        _ = 𝟙 _ := hsg

/-- A face followed by a degeneracy rewrites as a degeneracy followed by at most
one face. This is the generator-level critical pair in the canonical-form proof. -/
lemma face_degeneracy_factor (n : Dim) (i j : Fin (n + 1)) (α : Fin 2) :
    ∃ (Z : Dim) (ε : n ⟶ Z) (δ : Z ⟶ n),
      faceHom n i α ≫ degeneracyHom n j = ε ≫ δ ∧
        IsDegeneracyComposite ε ∧ IsFaceAtom δ := by
  cases n with
  | zero =>
      have hij : i = j := (Fin.eq_zero i).trans (Fin.eq_zero j).symm
      subst j
      refine ⟨0, 𝟙 0, 𝟙 0, ?_, .id 0, .id 0⟩
      apply CubeHom.ext
      apply OrderHom.ext
      funext x
      exact congrFun (insert_then_drop 0 i α) x
  | succ n =>
      rcases lt_trichotomy j i with hji | hji | hji
      · let j' : Fin (n + 1) := j.castLT (hji.trans_le (Fin.le_last i))
        let i' : Fin (n + 1) :=
          i.pred (ne_of_gt (lt_of_le_of_lt (Fin.zero_le j) hji))
        refine ⟨n, degeneracyHom n j', faceHom n i' α, ?_,
          .degeneracy n j', .face n i' α⟩
        apply CubeHom.ext
        apply OrderHom.ext
        funext x
        exact face_degeneracy_of_lt i j hji α x
      · subst j
        refine ⟨n + 1, 𝟙 (n + 1), 𝟙 (n + 1), ?_, .id _, .id _⟩
        apply CubeHom.ext
        apply OrderHom.ext
        funext x
        exact congrFun (insert_then_drop (n + 1) i α) x
      · let i' : Fin (n + 1) :=
          i.castLT (hji.trans_le (Fin.le_last j))
        let j' : Fin (n + 1) :=
          j.pred (ne_of_gt (lt_of_le_of_lt (Fin.zero_le i) hji))
        refine ⟨n, degeneracyHom n j', faceHom n i' α, ?_,
          .degeneracy n j', .face n i' α⟩
        apply CubeHom.ext
        apply OrderHom.ext
        funext x
        exact face_degeneracy_of_gt i j hji α x

/-- Commute an identity-or-single-face past an arbitrary degeneracy composite. -/
lemma faceAtom_degeneracyComposite_factor {n m k : Dim} {δ : n ⟶ m} {ε : m ⟶ k}
    (hδ : IsFaceAtom δ) (hε : IsDegeneracyComposite ε) :
    ∃ (Z : Dim) (ε' : n ⟶ Z) (δ' : Z ⟶ k),
      δ ≫ ε = ε' ≫ δ' ∧ IsDegeneracyComposite ε' ∧ IsFaceAtom δ' := by
  induction hε generalizing n with
  | id m =>
      refine ⟨n, 𝟙 n, δ, ?_, .id n, hδ⟩
      simp
  | degeneracy m j =>
      cases hδ with
      | id =>
          refine ⟨m, degeneracyHom m j, 𝟙 m, ?_, .degeneracy m j, .id m⟩
          simp
      | face i α =>
          exact face_degeneracy_factor m i j α
  | comp hε₁ hε₂ ih₁ ih₂ =>
      obtain ⟨Z₁, ε₁, δ₁, h₁, hε₁', hδ₁⟩ := ih₁ hδ
      obtain ⟨Z₂, ε₂, δ₂, h₂, hε₂', hδ₂⟩ := ih₂ hδ₁
      refine ⟨Z₂, ε₁ ≫ ε₂, δ₂, ?_, .comp hε₁' hε₂', hδ₂⟩
      calc
        δ ≫ (_ ≫ _) = (δ ≫ _) ≫ _ := (Category.assoc _ _ _).symm
        _ = (ε₁ ≫ δ₁) ≫ _ := by rw [h₁]
        _ = ε₁ ≫ (δ₁ ≫ _) := Category.assoc _ _ _
        _ = ε₁ ≫ (ε₂ ≫ δ₂) := by rw [h₂]
        _ = (ε₁ ≫ ε₂) ≫ δ₂ := (Category.assoc _ _ _).symm

/-- Commute an arbitrary face composite past an arbitrary degeneracy composite. -/
lemma faceComposite_degeneracyComposite_factor {n m k : Dim} {δ : n ⟶ m} {ε : m ⟶ k}
    (hδ : IsFaceComposite δ) (hε : IsDegeneracyComposite ε) :
    ∃ (Z : Dim) (ε' : n ⟶ Z) (δ' : Z ⟶ k),
      δ ≫ ε = ε' ≫ δ' ∧ IsDegeneracyComposite ε' ∧ IsFaceComposite δ' := by
  induction hδ generalizing k with
  | atom hδ =>
      obtain ⟨Z, ε', δ', h, hε', hδ'⟩ :=
        faceAtom_degeneracyComposite_factor hδ hε
      exact ⟨Z, ε', δ', h, hε', hδ'.isComposite⟩
  | comp hδ₁ hδ₂ ih₁ ih₂ =>
      obtain ⟨Z₂, ε₂, δ₂, h₂, hε₂, hδ₂'⟩ := ih₂ hε
      obtain ⟨Z₁, ε₁, δ₁, h₁, hε₁, hδ₁'⟩ := ih₁ hε₂
      refine ⟨Z₁, ε₁, δ₁ ≫ δ₂, ?_, hε₁, .comp hδ₁' hδ₂'⟩
      calc
        (_ ≫ _) ≫ ε = _ ≫ (_ ≫ ε) := Category.assoc _ _ _
        _ = _ ≫ (ε₂ ≫ δ₂) := by rw [h₂]
        _ = (_ ≫ ε₂) ≫ δ₂ := (Category.assoc _ _ _).symm
        _ = (ε₁ ≫ δ₁) ≫ δ₂ := by rw [h₁]
        _ = ε₁ ≫ (δ₁ ≫ δ₂) := Category.assoc _ _ _

/-- Every generated cube map has a syntactic degeneracy–face normal form. -/
lemma isGen_factorization {n m : Dim} {f : Cube n →o Cube m} (hf : IsGen n m f) :
    ∃ (Z : Dim) (ε : n ⟶ Z) (δ : Z ⟶ m),
      ε ≫ δ = ⟨f, hf⟩ ∧ IsDegeneracyComposite ε ∧ IsFaceComposite δ := by
  induction hf with
  | id n =>
      exact ⟨n, 𝟙 n, 𝟙 n, rfl, IsDegeneracyComposite.id n,
        (IsFaceAtom.id n).isComposite⟩
  | face n i α =>
      exact ⟨n, 𝟙 n, faceHom n i α, rfl, IsDegeneracyComposite.id n,
        (IsFaceAtom.face n i α).isComposite⟩
  | degeneracy n i =>
      exact ⟨n, degeneracyHom n i, 𝟙 n, rfl,
        IsDegeneracyComposite.degeneracy n i, (IsFaceAtom.id n).isComposite⟩
  | comp hf hg ihf ihg =>
      obtain ⟨Zf, εf, δf, hf_eq, hεf, hδf⟩ := ihf
      obtain ⟨Zg, εg, δg, hg_eq, hεg, hδg⟩ := ihg
      obtain ⟨Z, ε', δ', hcomm, hε', hδ'⟩ :=
        faceComposite_degeneracyComposite_factor hδf hεg
      refine ⟨Z, εf ≫ ε', δ' ≫ δg, ?_, .comp hεf hε', .comp hδ' hδg⟩
      calc
        (εf ≫ ε') ≫ δ' ≫ δg = εf ≫ (ε' ≫ δ') ≫ δg := by simp
        _ = εf ≫ (δf ≫ εg) ≫ δg := by rw [hcomm]
        _ = (εf ≫ δf) ≫ εg ≫ δg := by simp
        _ = _ := by
          rw [hf_eq, hg_eq]
          apply CubeHom.ext
          rfl

/-- The raising maps `R⁺`: order-embeddings (injective cube maps). These are
the composites of faces. -/
def plus : WideSubcategory Dim where
  hom _ _ f := Function.Injective ⇑f.toOrderHom
  id_mem _n _x _y h := h
  comp_mem hf hg := hg.comp hf

/-- The lowering maps `R⁻`: surjective cube maps. These are the composites of
degeneracies (all split epis on finite cubes). -/
def minus : WideSubcategory Dim where
  hom _ _ f := Function.Surjective ⇑f.toOrderHom
  id_mem _n x := ⟨x, rfl⟩
  comp_mem hf hg := hg.comp hf

/-!
## The generalized Reedy structure (Phase 2 skeleton)

Following Doherty (AGT 26:2, Prop 2.6) and Campion (arXiv:2303.06206, Thm 7.9),
the cubical site is a generalized Reedy category with `degree = id : ℕ → ℕ`:
raising maps are the injective cube maps (composites of faces), lowering maps
are the surjective cube maps (composites of degeneracies), and every map factors
as a degeneracy-composite followed by a face-composite (Grandis–Mauri eq. (6),
`f = ε ∘ δ`).

The `plus`/`minus` subcategories are defined above; the remaining axioms are
sorry'd and constitute the Phase 2 work.
-/

/-- The number of points of the `n`-cube is `2ⁿ`. -/
lemma card_cube (n : Dim) : Fintype.card (Cube n) = 2 ^ n := by
  classical
  simp [Cube]

/-- A monotone injection `2ⁿ → 2ᵐ` forces `n ≤ m` (comparing `2ⁿ ≤ 2ᵐ`). -/
lemma dim_le_of_injective {n m : Dim} {f : Cube n →o Cube m}
    (hf : Function.Injective ⇑f) : n ≤ m := by
  have h := Fintype.card_le_of_injective f hf
  rw [card_cube, card_cube] at h
  exact (Nat.pow_le_pow_iff_right (Nat.one_lt_two)).mp h

/-- A monotone surjection `2ⁿ → 2ᵐ` forces `m ≤ n` (comparing `2ⁿ ≥ 2ᵐ`). -/
lemma dim_le_of_surjective {n m : Dim} {f : Cube n →o Cube m}
    (hf : Function.Surjective ⇑f) : m ≤ n := by
  have h := Fintype.card_le_of_surjective f hf
  rw [card_cube, card_cube] at h
  exact (Nat.pow_le_pow_iff_right (Nat.one_lt_two)).mp h

/-- The underlying order-hom of an isomorphism in the site is bijective. -/
lemma bijective_of_isIso {n m : Dim} (f : n ⟶ m) (hf : IsIso f) :
    Function.Bijective ⇑f.toOrderHom := by
  obtain ⟨g, hgf, hfg⟩ := hf.out
  -- `f ≫ g = 𝟙 n` means `g.toOrderHom ∘ f.toOrderHom = id` and
  -- `g ≫ f = 𝟙 m` means `f.toOrderHom ∘ g.toOrderHom = id`, so they are inverse.
  have h1 : ⇑g.toOrderHom ∘ ⇑f.toOrderHom = _root_.id := by
    have h := congrArg (fun (e : n ⟶ n) => ⇑e.toOrderHom) hgf
    change ⇑(CubeHom.comp f g).toOrderHom = ⇑(CubeHom.id n).toOrderHom at h
    rw [CubeHom.comp_toOrderHom, CubeHom.id_toOrderHom] at h
    exact h
  have h2 : ⇑f.toOrderHom ∘ ⇑g.toOrderHom = _root_.id := by
    have h := congrArg (fun (e : m ⟶ m) => ⇑e.toOrderHom) hfg
    change ⇑(CubeHom.comp g f).toOrderHom = ⇑(CubeHom.id m).toOrderHom at h
    rw [CubeHom.comp_toOrderHom, CubeHom.id_toOrderHom] at h
    exact h
  exact Function.bijective_iff_has_inverse.mpr
    ⟨⇑g.toOrderHom, congrFun h1, congrFun h2⟩

/-- An isomorphism of generated cube maps `2ⁿ ≅ 2ᵐ` forces `n = m`. -/
lemma dim_eq_of_isIso {n m : Dim} (f : n ⟶ m) (hf : IsIso f) : n = m :=
  le_antisymm (dim_le_of_injective (bijective_of_isIso f hf).1)
    (dim_le_of_surjective (bijective_of_isIso f hf).2)

/-- A bijective monotone self-map of a cube is an order-isomorphism, hence (for
a generated map) an isomorphism in the site. -/
lemma isIso_of_bijective {n : Dim} {f : n ⟶ n} (hf : Function.Bijective ⇑f.toOrderHom) :
    IsIso f := by
  obtain ⟨Z, ε, δ, h, hε, hδ⟩ := isGen_factorization f.isGen
  have hnorm : ε ≫ δ = f := by
    apply CubeHom.ext
    exact congrArg CubeHom.toOrderHom h
  have hnorm_apply (x : Cube n) : δ.toOrderHom (ε.toOrderHom x) = f.toOrderHom x := by
    exact congrArg (fun q : n ⟶ n => q.toOrderHom x) hnorm
  have hεinj : Function.Injective ⇑ε.toOrderHom := by
    intro x y hxy
    apply hf.1
    rw [← hnorm_apply x, ← hnorm_apply y, hxy]
  have hδsurj : Function.Surjective ⇑δ.toOrderHom := by
    intro y
    obtain ⟨x, hx⟩ := hf.2 y
    refine ⟨ε.toOrderHom x, ?_⟩
    exact (hnorm_apply x).trans hx
  obtain ⟨sε, hsε⟩ := hε.hasSection
  obtain ⟨rδ, hrδ⟩ := hδ.hasRetraction
  have hεsε : ε ≫ sε = 𝟙 n := by
    apply CubeHom.ext
    apply OrderHom.ext
    funext x
    apply hεinj
    exact congrArg (fun q : Z ⟶ Z => q.toOrderHom (ε.toOrderHom x)) hsε
  have hrδδ : rδ ≫ δ = 𝟙 n := by
    apply CubeHom.ext
    apply OrderHom.ext
    funext y
    obtain ⟨x, rfl⟩ := hδsurj y
    have h' := congrArg (fun q : Z ⟶ Z => q.toOrderHom x) hrδ
    exact congrArg δ.toOrderHom h'
  letI : IsIso ε := ⟨⟨sε, hεsε, hsε⟩⟩
  letI : IsIso δ := ⟨⟨rδ, hrδ, hrδδ⟩⟩
  rw [← hnorm]
  infer_instance

/-- Cancel a surjective cube map on the left. -/
lemma cancel_precomposition_of_surjective {X Y Z : Dim} {f : X ⟶ Y} {g h : Y ⟶ Z}
    (hf : Function.Surjective ⇑f.toOrderHom) (w : f ≫ g = f ≫ h) : g = h := by
  apply CubeHom.ext
  apply OrderHom.ext
  funext y
  obtain ⟨x, rfl⟩ := hf y
  have w' := congrArg (fun q : X ⟶ Z => q.toOrderHom x) w
  exact w'

/-- Cancel an injective cube map on the right. -/
lemma cancel_postcomposition_of_injective {X Y Z : Dim} {f g : X ⟶ Y} {h : Y ⟶ Z}
    (hh : Function.Injective ⇑h.toOrderHom) (w : f ≫ h = g ≫ h) : f = g := by
  apply CubeHom.ext
  apply OrderHom.ext
  funext x
  apply hh
  have w' := congrArg (fun q : X ⟶ Z => q.toOrderHom x) w
  exact w'

/-- Every surjective generated cube map is a split epimorphism in the cubical site. -/
lemma hasSection_of_surjective {n m : Dim} (f : n ⟶ m)
    (hf : Function.Surjective ⇑f.toOrderHom) : ∃ s : m ⟶ n, s ≫ f = 𝟙 m := by
  obtain ⟨Z, ε, δ, h, hε, hδ⟩ := isGen_factorization f.isGen
  have hnorm : ε ≫ δ = f := by
    apply CubeHom.ext
    exact congrArg CubeHom.toOrderHom h
  have hδsurj : Function.Surjective ⇑δ.toOrderHom := by
    intro y
    obtain ⟨x, hx⟩ := hf y
    refine ⟨ε.toOrderHom x, ?_⟩
    have h' := congrArg (fun q : n ⟶ m => q.toOrderHom x) h
    exact h'.trans hx
  have hZm : Z = m :=
    le_antisymm (dim_le_of_injective hδ.injective) (dim_le_of_surjective hδsurj)
  subst m
  letI : IsIso δ := isIso_of_bijective ⟨hδ.injective, hδsurj⟩
  obtain ⟨sε, hsε⟩ := hε.hasSection
  refine ⟨inv δ ≫ sε, ?_⟩
  rw [← hnorm]
  calc
    (inv δ ≫ sε) ≫ (ε ≫ δ) = inv δ ≫ ((sε ≫ ε) ≫ δ) := by
      simp only [Category.assoc]
    _ = inv δ ≫ δ := by rw [hsε, Category.id_comp]
    _ = 𝟙 Z := IsIso.inv_hom_id_assoc δ (𝟙 Z)

/-- The degree of a cube is its dimension. -/
instance : BMGeneralizedReedyCategory Dim ℕ where
  plus := plus
  minus := minus
  degree n := n
  degree_lt_of_plus f hf hf_noniso := by
    have hle := dim_le_of_injective hf
    rcases hle.eq_or_lt with heq | hlt
    · -- `n = m` with `f` injective on a finite set ⇒ bijective ⇒ iso, contradicting `hf_noniso`.
      subst heq
      exact absurd
        (isIso_of_bijective ⟨hf, hf.surjective_of_finite (Equiv.refl _)⟩) hf_noniso
    · exact hlt
  degree_lt_of_minus f hf hf_noniso := by
    have hle := dim_le_of_surjective hf
    rcases hle.eq_or_lt with heq | hlt
    · -- `n = m` with `f` surjective on a finite set ⇒ bijective ⇒ iso, contradicting `hf_noniso`.
      subst heq
      exact absurd
        (isIso_of_bijective ⟨hf.injective_of_finite (Equiv.refl _), hf⟩) hf_noniso
    · exact hlt
  degree_eq_of_isIso f hf := dim_eq_of_isIso f hf
  isomorphisms_le_plus X Y f hf := (bijective_of_isIso f hf).1
  isomorphisms_le_minus X Y f hf := (bijective_of_isIso f hf).2
  factorization := by
    -- The canonical form (Grandis–Mauri eq. (6), Lemma 4.1): every generated map
    -- factors as a degeneracy-composite followed by a face-composite.
    constructor
    intro n m f
    obtain ⟨Z, ε, δ, h, hε, hδ⟩ := isGen_factorization f.isGen
    exact ⟨⟨Z, ε, δ, h, hε.surjective, hδ.injective⟩⟩

  factorization_unique f F G := by
    obtain ⟨sF, hsF⟩ := hasSection_of_surjective F.i F.hi
    obtain ⟨sG, hsG⟩ := hasSection_of_surjective G.i G.hi
    let e : F.Z ⟶ G.Z := sF ≫ G.i
    let e' : G.Z ⟶ F.Z := sG ≫ F.i
    have he_i : F.i ≫ e = G.i := by
      apply cancel_postcomposition_of_injective G.hp
      dsimp only [e]
      calc
        (F.i ≫ sF ≫ G.i) ≫ G.p = F.i ≫ (sF ≫ (G.i ≫ G.p)) := by
          simp only [Category.assoc]
        _ = F.i ≫ (sF ≫ f) := by rw [G.fac]
        _ = F.i ≫ (sF ≫ (F.i ≫ F.p)) := by rw [F.fac]
        _ = F.i ≫ F.p := by
          rw [← Category.assoc sF F.i F.p, hsF, Category.id_comp]
        _ = G.i ≫ G.p := F.fac.trans G.fac.symm
    have he'_i : G.i ≫ e' = F.i := by
      apply cancel_postcomposition_of_injective F.hp
      dsimp only [e']
      calc
        (G.i ≫ sG ≫ F.i) ≫ F.p = G.i ≫ (sG ≫ (F.i ≫ F.p)) := by
          simp only [Category.assoc]
        _ = G.i ≫ (sG ≫ f) := by rw [F.fac]
        _ = G.i ≫ (sG ≫ (G.i ≫ G.p)) := by rw [G.fac]
        _ = G.i ≫ G.p := by
          rw [← Category.assoc sG G.i G.p, hsG, Category.id_comp]
        _ = F.i ≫ F.p := G.fac.trans F.fac.symm
    have he_p : e ≫ G.p = F.p := by
      apply cancel_precomposition_of_surjective F.hi
      calc
        F.i ≫ (e ≫ G.p) = (F.i ≫ e) ≫ G.p := (Category.assoc _ _ _).symm
        _ = G.i ≫ G.p := by rw [he_i]
        _ = F.i ≫ F.p := G.fac.trans F.fac.symm
    have he_hom_inv : e ≫ e' = 𝟙 F.Z := by
      apply cancel_precomposition_of_surjective F.hi
      calc
        F.i ≫ (e ≫ e') = (F.i ≫ e) ≫ e' := (Category.assoc _ _ _).symm
        _ = G.i ≫ e' := by rw [he_i]
        _ = F.i := he'_i
        _ = F.i ≫ 𝟙 F.Z := (Category.comp_id _).symm
    have he_inv_hom : e' ≫ e = 𝟙 G.Z := by
      apply cancel_precomposition_of_surjective G.hi
      calc
        G.i ≫ (e' ≫ e) = (G.i ≫ e') ≫ e := (Category.assoc _ _ _).symm
        _ = F.i ≫ e := by rw [he'_i]
        _ = G.i := he_i
        _ = G.i ≫ 𝟙 G.Z := (Category.comp_id _).symm
    let E : F.Z ≅ G.Z :=
      { hom := e
        inv := e'
        hom_inv_id := he_hom_inv
        inv_hom_id := he_inv_hom }
    refine ⟨E, ⟨he_i, he_p⟩, ?_⟩
    intro E' hE'
    apply Iso.ext
    apply cancel_precomposition_of_surjective F.hi
    change F.i ≫ E'.hom = F.i ≫ e
    exact hE'.1.trans he_i.symm
  iso_eq_id_of_comp_minus f hf θ hθ h := by
    -- `f ≫ θ = f` with `f` surjective forces `θ = 𝟙`: `θ` fixes every point in
    -- the (full) image of `f`, and surjectivity makes that all of `Cube n`.
    apply CubeHom.ext
    apply OrderHom.ext
    funext y
    obtain ⟨x, rfl⟩ := hf y
    -- From `f ≫ θ = f` we get `(f ≫ θ).toOrderHom x = f.toOrderHom x`.
    have hcomp : (f ≫ θ).toOrderHom x = f.toOrderHom x := by
      have h' : (f ≫ θ).toOrderHom = f.toOrderHom := congrArg CubeHom.toOrderHom h
      rw [h']
    change (CubeHom.comp f θ).toOrderHom x = f.toOrderHom x at hcomp
    rw [CubeHom.comp_toOrderHom] at hcomp
    -- `hcomp : (θ.toOrderHom ∘ f.toOrderHom) x = f.toOrderHom x`, i.e. `θ (f x) = f x`;
    -- the RHS `(𝟙 Y).toOrderHom (f x)` reduces to `OrderHom.id (f x) = f x`.
    change θ.toOrderHom (f.toOrderHom x) = OrderHom.id (f.toOrderHom x)
    exact hcomp

end CubeSiteCategory

end Cubical

end HomologyLean.InfinityCategories
